# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcel_id', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('destination_address', models.PositiveIntegerField()),
                ('arrival_time', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.PositiveIntegerField()),
                ('address', models.IntegerField()),
                ('national_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone_number', models.PositiveIntegerField()),
                ('address', models.IntegerField()),
                ('national_id', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='parcel',
            name='receiver_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zigo.Receiver'),
        ),
        migrations.AddField(
            model_name='parcel',
            name='sender_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Zigo.Sender'),
        ),
    ]
